version: '3.8'

services:
    
    
   
    sprint:        
        image: saurabhdhumal/sprint2
        ports:
        - 8080:8080
     
  

    postgres:        
        image: postgres:14.5
        ports:
        - 5432:5432
       
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: scooby
            POSTGRES_DB: training

       
 
